// Decompiled with JetBrains decompiler
// Type: fCauHinhHienThi
// Assembly: MaxFarm_5_T3, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 27A477F0-955B-4C2D-A912-D8E1FD81A934
// Assembly location: C:\Users\Admin\Desktop\New folder\maxphonefarm_fb\maxphonefarm_fb\MaxFarm_5_T3.exe

using Bunifu.Framework.UI;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

public class fCauHinhHienThi : Form
{
  private IContainer icontainer_0 = (IContainer) null;
  private BunifuCards bunifuCards1;
  private Panel pnlHeader;
  private BunifuCustomLabel bunifuCustomLabel1;
  private Button btnMinimize;
  private Button btnCancel;
  private Button btnAdd;
  private BunifuDragControl bunifuDragControl_0;
  private BunifuCustomLabel lblStatus;
  private CheckBox ckbToken;
  private CheckBox ckbCookie;
  private CheckBox ckbEmail;
  private CheckBox ckbTen;
  private CheckBox ckbBanBe;
  private CheckBox ckbNhom;
  private CheckBox ckbNgaySinh;
  private CheckBox ckbGioiTinh;
  private CheckBox ckbMatKhau;
  private CheckBox ckbMatKhauMail;
  private CheckBox ckbBackup;
  private CheckBox ckbMa2FA;
  private CheckBox ckbUseragent;
  private CheckBox ckbProxy;
  private CheckBox ckbNgayTao;
  private CheckBox ckbAvatar;
  private CheckBox ckbProfile;
  private CheckBox ckbTinhTrang;
  private CheckBox ckbGhiChu;
  private CheckBox ckbThuMuc;
  private CheckBox ckbFollow;
  private CheckBox ckbInteractEnd;
  private CheckBox ckbDevice;
  private IContainer components;
  private CheckBox ckbPhone;

  public fCauHinhHienThi()
  {
    this.InitializeComponent();
    GClass35.smethod_5((Control) this);
  }

  private void btnMinimize_Click(object sender, EventArgs e) => this.Close();

  private void btnAdd_Click(object sender, EventArgs e)
  {
    GClass33.smethod_0("configDatagridview").method_6("cToken", (object) this.ckbToken.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbCookie", (object) this.ckbCookie.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbEmail", (object) this.ckbEmail.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbTen", (object) this.ckbTen.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbBanBe", (object) this.ckbBanBe.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbNhom", (object) this.ckbNhom.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbNgaySinh", (object) this.ckbNgaySinh.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbGioiTinh", (object) this.ckbGioiTinh.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbMatKhau", (object) this.ckbMatKhau.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbMatKhauMail", (object) this.ckbMatKhauMail.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbPhone", (object) this.ckbPhone.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbBackup", (object) this.ckbBackup.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbMa2FA", (object) this.ckbMa2FA.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbUseragent", (object) this.ckbUseragent.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbProxy", (object) this.ckbProxy.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbNgayTao", (object) this.ckbNgayTao.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbAvatar", (object) this.ckbAvatar.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbProfile", (object) this.ckbProfile.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbTinhTrang", (object) this.ckbTinhTrang.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbThuMuc", (object) this.ckbThuMuc.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbGhiChu", (object) this.ckbGhiChu.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbFollow", (object) this.ckbFollow.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbInteractEnd", (object) this.ckbInteractEnd.Checked);
    GClass33.smethod_0("configDatagridview").method_6("ckbDevice", (object) this.ckbDevice.Checked);
    GClass33.smethod_2("configDatagridview");
    this.Close();
  }

  private void btnCancel_Click(object sender, EventArgs e) => this.Close();

  private void lblStatus_Click(object sender, EventArgs e)
  {
  }

  private void fCauHinhHienThi_Load(object sender, EventArgs e)
  {
    this.ckbToken.Checked = GClass33.smethod_0("configDatagridview").method_4("cToken");
    this.ckbCookie.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbCookie");
    this.ckbEmail.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbEmail");
    this.ckbTen.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbTen");
    this.ckbBanBe.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbBanBe");
    this.ckbNhom.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbNhom");
    this.ckbNgaySinh.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbNgaySinh");
    this.ckbGioiTinh.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbGioiTinh");
    this.ckbMatKhau.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbMatKhau");
    this.ckbMatKhauMail.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbMatKhauMail");
    this.ckbPhone.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbPhone");
    this.ckbBackup.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbBackup");
    this.ckbMa2FA.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbMa2FA");
    this.ckbUseragent.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbUseragent");
    this.ckbProxy.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbProxy");
    this.ckbNgayTao.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbNgayTao");
    this.ckbAvatar.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbAvatar");
    this.ckbProfile.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbProfile");
    this.ckbTinhTrang.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbTinhTrang");
    this.ckbThuMuc.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbThuMuc");
    this.ckbGhiChu.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbGhiChu");
    this.ckbFollow.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbFollow");
    this.ckbInteractEnd.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbInteractEnd");
    this.ckbDevice.Checked = GClass33.smethod_0("configDatagridview").method_4("ckbDevice");
  }

  protected override void Dispose(bool disposing)
  {
    if (disposing && this.icontainer_0 != null)
      this.icontainer_0.Dispose();
    base.Dispose(disposing);
  }

  private void InitializeComponent()
  {
    this.components = (IContainer) new System.ComponentModel.Container();
    ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (fCauHinhHienThi));
    this.bunifuCards1 = new BunifuCards();
    this.pnlHeader = new Panel();
    this.btnMinimize = new Button();
    this.bunifuCustomLabel1 = new BunifuCustomLabel();
    this.btnCancel = new Button();
    this.btnAdd = new Button();
    this.bunifuDragControl_0 = new BunifuDragControl(this.components);
    this.lblStatus = new BunifuCustomLabel();
    this.ckbToken = new CheckBox();
    this.ckbCookie = new CheckBox();
    this.ckbEmail = new CheckBox();
    this.ckbTen = new CheckBox();
    this.ckbBanBe = new CheckBox();
    this.ckbNhom = new CheckBox();
    this.ckbNgaySinh = new CheckBox();
    this.ckbGioiTinh = new CheckBox();
    this.ckbMatKhau = new CheckBox();
    this.ckbMatKhauMail = new CheckBox();
    this.ckbBackup = new CheckBox();
    this.ckbMa2FA = new CheckBox();
    this.ckbUseragent = new CheckBox();
    this.ckbProxy = new CheckBox();
    this.ckbNgayTao = new CheckBox();
    this.ckbAvatar = new CheckBox();
    this.ckbProfile = new CheckBox();
    this.ckbTinhTrang = new CheckBox();
    this.ckbGhiChu = new CheckBox();
    this.ckbThuMuc = new CheckBox();
    this.ckbFollow = new CheckBox();
    this.ckbInteractEnd = new CheckBox();
    this.ckbDevice = new CheckBox();
    this.ckbPhone = new CheckBox();
    this.bunifuCards1.SuspendLayout();
    this.pnlHeader.SuspendLayout();
    this.SuspendLayout();
    this.bunifuCards1.BackColor = Color.White;
    this.bunifuCards1.BorderRadius = 0;
    this.bunifuCards1.BottomSahddow = true;
    this.bunifuCards1.color = Color.SaddleBrown;
    this.bunifuCards1.Controls.Add((Control) this.pnlHeader);
    this.bunifuCards1.Dock = DockStyle.Top;
    this.bunifuCards1.LeftSahddow = false;
    this.bunifuCards1.Location = new Point(0, 0);
    this.bunifuCards1.Name = "bunifuCards1";
    this.bunifuCards1.RightSahddow = true;
    this.bunifuCards1.ShadowDepth = 20;
    this.bunifuCards1.Size = new Size(479, 38);
    this.bunifuCards1.TabIndex = 0;
    this.pnlHeader.Anchor = AnchorStyles.Left | AnchorStyles.Right;
    this.pnlHeader.BackColor = Color.White;
    this.pnlHeader.Controls.Add((Control) this.btnMinimize);
    this.pnlHeader.Controls.Add((Control) this.bunifuCustomLabel1);
    this.pnlHeader.Location = new Point(0, 5);
    this.pnlHeader.Name = "pnlHeader";
    this.pnlHeader.Size = new Size(479, 32);
    this.pnlHeader.TabIndex = 9;
    this.btnMinimize.Cursor = Cursors.Hand;
    this.btnMinimize.Dock = DockStyle.Right;
    this.btnMinimize.FlatAppearance.BorderSize = 0;
    this.btnMinimize.FlatStyle = FlatStyle.Flat;
    this.btnMinimize.Font = new Font("Microsoft Sans Serif", 11.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.btnMinimize.ForeColor = Color.White;
    this.btnMinimize.Image = (Image) componentResourceManager.GetObject("btnMinimize.Image");
    this.btnMinimize.Location = new Point(447, 0);
    this.btnMinimize.Name = "btnMinimize";
    this.btnMinimize.Size = new Size(32, 32);
    this.btnMinimize.TabIndex = 9;
    this.btnMinimize.TextImageRelation = TextImageRelation.ImageBeforeText;
    this.btnMinimize.UseVisualStyleBackColor = true;
    this.btnMinimize.Click += new EventHandler(this.btnMinimize_Click);
    this.bunifuCustomLabel1.BackColor = Color.Transparent;
    this.bunifuCustomLabel1.Cursor = Cursors.SizeAll;
    this.bunifuCustomLabel1.Dock = DockStyle.Fill;
    this.bunifuCustomLabel1.Font = new Font("Tahoma", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.bunifuCustomLabel1.ForeColor = Color.Black;
    this.bunifuCustomLabel1.Location = new Point(0, 0);
    this.bunifuCustomLabel1.Name = "bunifuCustomLabel1";
    this.bunifuCustomLabel1.Size = new Size(479, 32);
    this.bunifuCustomLabel1.TabIndex = 1;
    this.bunifuCustomLabel1.Text = "Cấu hình hiển thị";
    this.bunifuCustomLabel1.TextAlign = ContentAlignment.MiddleCenter;
    this.btnCancel.BackColor = Color.Maroon;
    this.btnCancel.Cursor = Cursors.Hand;
    this.btnCancel.FlatAppearance.BorderSize = 0;
    this.btnCancel.FlatStyle = FlatStyle.Flat;
    this.btnCancel.Font = new Font("Tahoma", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.btnCancel.ForeColor = Color.White;
    this.btnCancel.Location = new Point(247, 253);
    this.btnCancel.Name = "btnCancel";
    this.btnCancel.Size = new Size(92, 29);
    this.btnCancel.TabIndex = 4;
    this.btnCancel.Text = "Đóng";
    this.btnCancel.UseVisualStyleBackColor = false;
    this.btnCancel.Click += new EventHandler(this.btnCancel_Click);
    this.btnAdd.BackColor = Color.FromArgb(53, 120, 229);
    this.btnAdd.Cursor = Cursors.Hand;
    this.btnAdd.FlatAppearance.BorderSize = 0;
    this.btnAdd.FlatStyle = FlatStyle.Flat;
    this.btnAdd.Font = new Font("Tahoma", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.btnAdd.ForeColor = Color.White;
    this.btnAdd.Location = new Point(143, 253);
    this.btnAdd.Name = "btnAdd";
    this.btnAdd.Size = new Size(92, 29);
    this.btnAdd.TabIndex = 3;
    this.btnAdd.Text = "Lưu";
    this.btnAdd.UseVisualStyleBackColor = false;
    this.btnAdd.Click += new EventHandler(this.btnAdd_Click);
    this.bunifuDragControl_0.Fixed = true;
    this.bunifuDragControl_0.Horizontal = true;
    this.bunifuDragControl_0.TargetControl = (Control) this.bunifuCustomLabel1;
    this.bunifuDragControl_0.Vertical = true;
    this.lblStatus.BackColor = Color.Transparent;
    this.lblStatus.Cursor = Cursors.SizeAll;
    this.lblStatus.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.lblStatus.ForeColor = Color.Black;
    this.lblStatus.Location = new Point(51, 41);
    this.lblStatus.Name = "lblStatus";
    this.lblStatus.Size = new Size(384, 32);
    this.lblStatus.TabIndex = 21;
    this.lblStatus.Text = "Vui lòng chọn những cột cần hiển thị!";
    this.lblStatus.TextAlign = ContentAlignment.MiddleCenter;
    this.lblStatus.Click += new EventHandler(this.lblStatus_Click);
    this.ckbToken.AutoSize = true;
    this.ckbToken.Cursor = Cursors.Hand;
    this.ckbToken.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbToken.Location = new Point(31, 85);
    this.ckbToken.Name = "ckbToken";
    this.ckbToken.Size = new Size(61, 20);
    this.ckbToken.TabIndex = 22;
    this.ckbToken.Text = "Token";
    this.ckbToken.UseVisualStyleBackColor = true;
    this.ckbCookie.AutoSize = true;
    this.ckbCookie.Cursor = Cursors.Hand;
    this.ckbCookie.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbCookie.Location = new Point(31, 111);
    this.ckbCookie.Name = "ckbCookie";
    this.ckbCookie.Size = new Size(64, 20);
    this.ckbCookie.TabIndex = 22;
    this.ckbCookie.Text = "Cookie";
    this.ckbCookie.UseVisualStyleBackColor = true;
    this.ckbEmail.AutoSize = true;
    this.ckbEmail.Cursor = Cursors.Hand;
    this.ckbEmail.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbEmail.Location = new Point(31, 137);
    this.ckbEmail.Name = "ckbEmail";
    this.ckbEmail.Size = new Size(57, 20);
    this.ckbEmail.TabIndex = 22;
    this.ckbEmail.Text = "Email";
    this.ckbEmail.UseVisualStyleBackColor = true;
    this.ckbTen.AutoSize = true;
    this.ckbTen.Cursor = Cursors.Hand;
    this.ckbTen.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbTen.Location = new Point(31, 163);
    this.ckbTen.Name = "ckbTen";
    this.ckbTen.Size = new Size(48, 20);
    this.ckbTen.TabIndex = 22;
    this.ckbTen.Text = "Tên";
    this.ckbTen.UseVisualStyleBackColor = true;
    this.ckbBanBe.AutoSize = true;
    this.ckbBanBe.Cursor = Cursors.Hand;
    this.ckbBanBe.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbBanBe.Location = new Point(31, 215);
    this.ckbBanBe.Name = "ckbBanBe";
    this.ckbBanBe.Size = new Size(65, 20);
    this.ckbBanBe.TabIndex = 22;
    this.ckbBanBe.Text = "Bạn bè";
    this.ckbBanBe.UseVisualStyleBackColor = true;
    this.ckbNhom.AutoSize = true;
    this.ckbNhom.Cursor = Cursors.Hand;
    this.ckbNhom.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbNhom.Location = new Point(128, 85);
    this.ckbNhom.Name = "ckbNhom";
    this.ckbNhom.Size = new Size(59, 20);
    this.ckbNhom.TabIndex = 22;
    this.ckbNhom.Text = "Nhóm";
    this.ckbNhom.UseVisualStyleBackColor = true;
    this.ckbNgaySinh.AutoSize = true;
    this.ckbNgaySinh.Cursor = Cursors.Hand;
    this.ckbNgaySinh.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbNgaySinh.Location = new Point(128, 111);
    this.ckbNgaySinh.Name = "ckbNgaySinh";
    this.ckbNgaySinh.Size = new Size(81, 20);
    this.ckbNgaySinh.TabIndex = 22;
    this.ckbNgaySinh.Text = "Ngày sinh";
    this.ckbNgaySinh.UseVisualStyleBackColor = true;
    this.ckbGioiTinh.AutoSize = true;
    this.ckbGioiTinh.Cursor = Cursors.Hand;
    this.ckbGioiTinh.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbGioiTinh.Location = new Point(128, 137);
    this.ckbGioiTinh.Name = "ckbGioiTinh";
    this.ckbGioiTinh.Size = new Size(72, 20);
    this.ckbGioiTinh.TabIndex = 22;
    this.ckbGioiTinh.Text = "Giới tính";
    this.ckbGioiTinh.UseVisualStyleBackColor = true;
    this.ckbMatKhau.AutoSize = true;
    this.ckbMatKhau.Cursor = Cursors.Hand;
    this.ckbMatKhau.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbMatKhau.Location = new Point(128, 163);
    this.ckbMatKhau.Name = "ckbMatKhau";
    this.ckbMatKhau.Size = new Size(78, 20);
    this.ckbMatKhau.TabIndex = 22;
    this.ckbMatKhau.Text = "Mật khẩu";
    this.ckbMatKhau.UseVisualStyleBackColor = true;
    this.ckbMatKhauMail.AutoSize = true;
    this.ckbMatKhauMail.Cursor = Cursors.Hand;
    this.ckbMatKhauMail.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbMatKhauMail.Location = new Point(128, 189);
    this.ckbMatKhauMail.Name = "ckbMatKhauMail";
    this.ckbMatKhauMail.Size = new Size(106, 20);
    this.ckbMatKhauMail.TabIndex = 22;
    this.ckbMatKhauMail.Text = "Mật khẩu mail";
    this.ckbMatKhauMail.UseVisualStyleBackColor = true;
    this.ckbBackup.AutoSize = true;
    this.ckbBackup.Cursor = Cursors.Hand;
    this.ckbBackup.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbBackup.Location = new Point(253, 111);
    this.ckbBackup.Name = "ckbBackup";
    this.ckbBackup.Size = new Size(66, 20);
    this.ckbBackup.TabIndex = 22;
    this.ckbBackup.Text = "Backup";
    this.ckbBackup.UseVisualStyleBackColor = true;
    this.ckbMa2FA.AutoSize = true;
    this.ckbMa2FA.Cursor = Cursors.Hand;
    this.ckbMa2FA.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbMa2FA.Location = new Point(253, 85);
    this.ckbMa2FA.Name = "ckbMa2FA";
    this.ckbMa2FA.Size = new Size(69, 20);
    this.ckbMa2FA.TabIndex = 22;
    this.ckbMa2FA.Text = "Mã 2FA";
    this.ckbMa2FA.UseVisualStyleBackColor = true;
    this.ckbUseragent.AutoSize = true;
    this.ckbUseragent.Cursor = Cursors.Hand;
    this.ckbUseragent.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbUseragent.Location = new Point(253, 137);
    this.ckbUseragent.Name = "ckbUseragent";
    this.ckbUseragent.Size = new Size(84, 20);
    this.ckbUseragent.TabIndex = 22;
    this.ckbUseragent.Text = "Useragent";
    this.ckbUseragent.UseVisualStyleBackColor = true;
    this.ckbProxy.AutoSize = true;
    this.ckbProxy.Cursor = Cursors.Hand;
    this.ckbProxy.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbProxy.Location = new Point(253, 163);
    this.ckbProxy.Name = "ckbProxy";
    this.ckbProxy.Size = new Size(57, 20);
    this.ckbProxy.TabIndex = 22;
    this.ckbProxy.Text = "Proxy";
    this.ckbProxy.UseVisualStyleBackColor = true;
    this.ckbNgayTao.AutoSize = true;
    this.ckbNgayTao.Cursor = Cursors.Hand;
    this.ckbNgayTao.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbNgayTao.Location = new Point(253, 189);
    this.ckbNgayTao.Name = "ckbNgayTao";
    this.ckbNgayTao.Size = new Size(76, 20);
    this.ckbNgayTao.TabIndex = 22;
    this.ckbNgayTao.Text = "Ngày tạo";
    this.ckbNgayTao.UseVisualStyleBackColor = true;
    this.ckbAvatar.AutoSize = true;
    this.ckbAvatar.Cursor = Cursors.Hand;
    this.ckbAvatar.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbAvatar.Location = new Point(253, 215);
    this.ckbAvatar.Name = "ckbAvatar";
    this.ckbAvatar.Size = new Size(63, 20);
    this.ckbAvatar.TabIndex = 22;
    this.ckbAvatar.Text = "Avatar";
    this.ckbAvatar.UseVisualStyleBackColor = true;
    this.ckbProfile.AutoSize = true;
    this.ckbProfile.Cursor = Cursors.Hand;
    this.ckbProfile.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbProfile.Location = new Point(356, 85);
    this.ckbProfile.Name = "ckbProfile";
    this.ckbProfile.Size = new Size(62, 20);
    this.ckbProfile.TabIndex = 22;
    this.ckbProfile.Text = "Profile";
    this.ckbProfile.UseVisualStyleBackColor = true;
    this.ckbTinhTrang.AutoSize = true;
    this.ckbTinhTrang.Cursor = Cursors.Hand;
    this.ckbTinhTrang.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbTinhTrang.Location = new Point(356, 163);
    this.ckbTinhTrang.Name = "ckbTinhTrang";
    this.ckbTinhTrang.Size = new Size(85, 20);
    this.ckbTinhTrang.TabIndex = 22;
    this.ckbTinhTrang.Text = "Tình trạng";
    this.ckbTinhTrang.UseVisualStyleBackColor = true;
    this.ckbGhiChu.AutoSize = true;
    this.ckbGhiChu.Cursor = Cursors.Hand;
    this.ckbGhiChu.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbGhiChu.Location = new Point(356, 215);
    this.ckbGhiChu.Name = "ckbGhiChu";
    this.ckbGhiChu.Size = new Size(68, 20);
    this.ckbGhiChu.TabIndex = 22;
    this.ckbGhiChu.Text = "Ghi chú";
    this.ckbGhiChu.UseVisualStyleBackColor = true;
    this.ckbThuMuc.AutoSize = true;
    this.ckbThuMuc.Cursor = Cursors.Hand;
    this.ckbThuMuc.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbThuMuc.Location = new Point(356, 189);
    this.ckbThuMuc.Name = "ckbThuMuc";
    this.ckbThuMuc.Size = new Size(77, 20);
    this.ckbThuMuc.TabIndex = 22;
    this.ckbThuMuc.Text = "Thư mục";
    this.ckbThuMuc.UseVisualStyleBackColor = true;
    this.ckbFollow.AutoSize = true;
    this.ckbFollow.Cursor = Cursors.Hand;
    this.ckbFollow.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbFollow.Location = new Point(31, 189);
    this.ckbFollow.Name = "ckbFollow";
    this.ckbFollow.Size = new Size(76, 20);
    this.ckbFollow.TabIndex = 22;
    this.ckbFollow.Text = "Theo dõi";
    this.ckbFollow.UseVisualStyleBackColor = true;
    this.ckbInteractEnd.AutoSize = true;
    this.ckbInteractEnd.Cursor = Cursors.Hand;
    this.ckbInteractEnd.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbInteractEnd.Location = new Point(356, 111);
    this.ckbInteractEnd.Name = "ckbInteractEnd";
    this.ckbInteractEnd.Size = new Size(111, 20);
    this.ckbInteractEnd.TabIndex = 22;
    this.ckbInteractEnd.Text = "Tương tác cuối";
    this.ckbInteractEnd.UseVisualStyleBackColor = true;
    this.ckbDevice.AutoSize = true;
    this.ckbDevice.Cursor = Cursors.Hand;
    this.ckbDevice.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbDevice.Location = new Point(356, 137);
    this.ckbDevice.Name = "ckbDevice";
    this.ckbDevice.Size = new Size(89, 20);
    this.ckbDevice.TabIndex = 22;
    this.ckbDevice.Text = "Device Info";
    this.ckbDevice.UseVisualStyleBackColor = true;
    this.ckbPhone.AutoSize = true;
    this.ckbPhone.Cursor = Cursors.Hand;
    this.ckbPhone.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ckbPhone.Location = new Point(128, 215);
    this.ckbPhone.Name = "ckbPhone";
    this.ckbPhone.Size = new Size(61, 20);
    this.ckbPhone.TabIndex = 22;
    this.ckbPhone.Text = "Phone";
    this.ckbPhone.UseVisualStyleBackColor = true;
    this.AutoScaleDimensions = new SizeF(6f, 13f);
    this.AutoScaleMode = AutoScaleMode.Font;
    this.ClientSize = new Size(479, 295);
    this.Controls.Add((Control) this.ckbThuMuc);
    this.Controls.Add((Control) this.ckbGhiChu);
    this.Controls.Add((Control) this.ckbInteractEnd);
    this.Controls.Add((Control) this.ckbTinhTrang);
    this.Controls.Add((Control) this.ckbProfile);
    this.Controls.Add((Control) this.ckbAvatar);
    this.Controls.Add((Control) this.ckbNgayTao);
    this.Controls.Add((Control) this.ckbProxy);
    this.Controls.Add((Control) this.ckbUseragent);
    this.Controls.Add((Control) this.ckbMa2FA);
    this.Controls.Add((Control) this.ckbBackup);
    this.Controls.Add((Control) this.ckbPhone);
    this.Controls.Add((Control) this.ckbMatKhauMail);
    this.Controls.Add((Control) this.ckbMatKhau);
    this.Controls.Add((Control) this.ckbGioiTinh);
    this.Controls.Add((Control) this.ckbNgaySinh);
    this.Controls.Add((Control) this.ckbNhom);
    this.Controls.Add((Control) this.ckbFollow);
    this.Controls.Add((Control) this.ckbBanBe);
    this.Controls.Add((Control) this.ckbTen);
    this.Controls.Add((Control) this.ckbEmail);
    this.Controls.Add((Control) this.ckbCookie);
    this.Controls.Add((Control) this.ckbToken);
    this.Controls.Add((Control) this.lblStatus);
    this.Controls.Add((Control) this.btnCancel);
    this.Controls.Add((Control) this.btnAdd);
    this.Controls.Add((Control) this.bunifuCards1);
    this.Controls.Add((Control) this.ckbDevice);
    this.FormBorderStyle = FormBorderStyle.None;
    this.Name = nameof (fCauHinhHienThi);
    this.StartPosition = FormStartPosition.CenterParent;
    this.Text = "fAddFile";
    this.Load += new EventHandler(this.fCauHinhHienThi_Load);
    this.bunifuCards1.ResumeLayout(false);
    this.pnlHeader.ResumeLayout(false);
    this.ResumeLayout(false);
    this.PerformLayout();
  }
}
